version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poc_login_empodera
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./startup.sh:/app/startup.sh
    command: bash -c "bash startup.sh && tail -f /dev/null"
